import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from '@tanstack/react-router';
import { useMemo, useState } from 'react';
import { GitCompare, Trash2 } from 'lucide-react';
import { api } from '~/api/client';
import type { ApiPlan, ApiPlanDetail } from '~/api/types';
import { Button } from '~/components/Button';
import { Callout } from '~/components/Callout';
import { Dialog } from '~/components/Dialog';
import { Markdown } from '~/components/Markdown';
import { Page } from '~/components/Page';
import { useConfirm } from '~/components/Confirm';
import { useToast } from '~/components/Toast';

export function PlanDetail() {
  const { feature, planFile } = useParams({ from: '/plans/$feature/$planFile' });
  const navigate = useNavigate();
  const qc = useQueryClient();
  const confirm = useConfirm();
  const { toast } = useToast();
  const [compareOpen, setCompareOpen] = useState(false);
  const [trash, setTrash] = useState(true);
  const [copyHint, setCopyHint] = useState<string | null>(null);

  const q = useQuery({
    queryKey: ['plan', feature, planFile],
    queryFn: () =>
      api<ApiPlanDetail>(
        `/api/plans/${encodeURIComponent(feature)}/${encodeURIComponent(planFile)}`,
      ),
  });
  const allPlans = useQuery({ queryKey: ['plans'], queryFn: () => api<ApiPlan[]>('/api/plans') });

  const sameFeature = useMemo(
    () => (allPlans.data ?? []).filter((p) => p.feature === feature && p.planFile !== planFile),
    [allPlans.data, feature, planFile],
  );

  const delM = useMutation({
    mutationFn: () =>
      api(
        `/api/plans/${encodeURIComponent(feature)}/${encodeURIComponent(planFile)}?trash=${trash ? '1' : '0'}`,
        { method: 'DELETE' },
      ),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ['plans'] });
      toast({ tone: 'success', title: 'Plan deleted' });
      void navigate({ to: '/plans' } as never);
    },
  });

  async function onDelete() {
    const ok = await confirm({
      title: `Delete ${planFile}?`,
      description: `Remove ${planFile} ${trash ? 'to the trash folder' : 'permanently'}.`,
      tone: 'danger',
      confirmLabel: 'Delete plan',
    });
    if (!ok) return;
    delM.mutate();
  }

  if (q.isLoading) {
    return (
      <Page title={planFile} description="…">
        <p className="text-[var(--color-text-muted)]">Loading…</p>
      </Page>
    );
  }
  if (q.isError) {
    return (
      <Page title={planFile} description="…">
        <Callout tone="danger">{(q.error as Error).message}</Callout>
      </Page>
    );
  }
  if (!q.data) return null;

  const d = q.data;
  const metaLine = d.metadata?.generatedBy
    ? `${d.metadata.provider ?? ''}/${d.metadata.model ?? d.metadata.generatedBy}`.replace(/^\//, '')
    : '—';

  const openVscode = () => {
    const p = d.absPath;
    window.location.href = `vscode://file${p.startsWith('/') ? '' : '/'}${p}`.replace(/\s/g, '%20');
  };

  const copyPath = async () => {
    try {
      await navigator.clipboard.writeText(d.absPath);
      setCopyHint('Path copied');
      setTimeout(() => setCopyHint(null), 2000);
    } catch {
      setCopyHint('Copy failed (browser blocked)');
    }
  };

  return (
    <Page
      title={<span className="break-all font-mono">{d.planFile}</span>}
      description={`Generated by ${metaLine}`}
      actions={
        <div className="flex flex-wrap items-center gap-2">
          <Button type="button" variant="secondary" onClick={openVscode}>
            Open in editor
          </Button>
          <Button type="button" variant="secondary" onClick={copyPath}>
            Copy path
          </Button>
          {copyHint ? <span className="text-xs text-[var(--color-text-muted)]">{copyHint}</span> : null}
          {sameFeature.length > 0 ? (
            <Button type="button" variant="secondary" leftIcon={<GitCompare size={14} />} onClick={() => setCompareOpen(true)}>
              Compare with…
            </Button>
          ) : null}
          <Button type="button" variant="danger" leftIcon={<Trash2 size={14} />} onClick={() => void onDelete()}>
            Delete plan
          </Button>
        </div>
      }
    >
      <div className="mb-4 text-sm">
        <Link to={'/plans' as never} className="text-[var(--color-text-muted)] hover:text-[var(--color-text)]">
          ← Plans
        </Link>
      </div>
      <label className="mb-4 flex items-center gap-2 text-sm text-[var(--color-text-muted)]">
        <input type="checkbox" checked={trash} onChange={(e) => setTrash(e.target.checked)} className="rounded" />
        Move to trash
      </label>
      <details className="mb-6 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-elevated)] p-3 text-sm">
        <summary className="cursor-pointer text-[var(--color-text-dim)]">Metadata</summary>
        <pre className="mt-2 overflow-x-auto text-xs text-[var(--color-text-muted)]">
          {JSON.stringify(d.metadata, null, 2)}
        </pre>
      </details>
      <Markdown source={d.content} />
      <Dialog
        open={compareOpen}
        onClose={() => setCompareOpen(false)}
        title="Compare with"
        footer={
          <Button type="button" variant="secondary" onClick={() => setCompareOpen(false)}>
            Close
          </Button>
        }
      >
        <ul className="space-y-1">
          {sameFeature.map((p) => (
            <li key={p.planFile}>
              <button
                type="button"
                className="w-full text-left font-mono text-sm text-[var(--color-accent)] hover:underline"
                onClick={() => {
                  setCompareOpen(false);
                  void navigate({
                    to: '/plans/$feature/diff',
                    params: { feature },
                    search: { a: planFile, b: p.planFile },
                  });
                }}
              >
                {p.planFile}
              </button>
            </li>
          ))}
        </ul>
      </Dialog>
    </Page>
  );
}
