import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { readPlanMetadata } from '../src/core/stories.js';

let tmp: string;

beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'squad-list-col-'));
});

afterEach(() => {
  fs.rmSync(tmp, { recursive: true, force: true });
});

describe('readPlanMetadata', () => {
  it('parses first-line API metadata comment', () => {
    const f = path.join(tmp, 'plan.md');
    fs.writeFileSync(
      f,
      '<!-- squad-kit: generated by anthropic/claude-opus-4-x, at 2026-01-01T00:00:00.000Z, 0 reads / 0.0 KB context, 1 in / 2 out tokens -->\n# Plan\n',
      'utf8',
    );
    expect(readPlanMetadata(f)).toEqual({
      provider: 'anthropic',
      model: 'claude-opus-4-x',
      generatedBy: 'anthropic/claude-opus-4-x',
    });
  });

  it('returns empty object when first line is plain markdown', () => {
    const f = path.join(tmp, 'plain.md');
    fs.writeFileSync(f, '# No comment here\n', 'utf8');
    expect(readPlanMetadata(f)).toEqual({});
  });

  it('finds metadata after leading blank lines or BOM', () => {
    const f = path.join(tmp, 'offset-meta.md');
    const meta =
      '<!-- squad-kit: generated by anthropic/claude-opus-4-x, at 2026-01-01T00:00:00.000Z, 0 reads / 0.0 KB context, 1 in / 2 out tokens -->';
    fs.writeFileSync(f, `\n\n${meta}\n# Plan\n`, 'utf8');
    expect(readPlanMetadata(f)).toEqual({
      provider: 'anthropic',
      model: 'claude-opus-4-x',
      generatedBy: 'anthropic/claude-opus-4-x',
    });

    const f2 = path.join(tmp, 'bom-meta.md');
    fs.writeFileSync(f2, `\uFEFF\n${meta}\n`, 'utf8');
    expect(readPlanMetadata(f2).generatedBy).toBe('anthropic/claude-opus-4-x');
  });

  it('parses non-API squad-kit header as generatedBy text', () => {
    const f = path.join(tmp, 'custom-meta.md');
    fs.writeFileSync(
      f,
      '<!-- squad-kit: plan for story 1; implementation completed 2026-04-25 -->\n# Plan\n',
      'utf8',
    );
    expect(readPlanMetadata(f)).toEqual({
      generatedBy: 'plan for story 1; implementation completed 2026-04-25',
    });
  });
});
