import path from 'node:path';
import * as ui from '../ui/index.js';
import { buildPaths, requireSquadRoot } from '../core/paths.js';
import { type PlanMetadata, listStories, readPlanMetadata } from '../core/stories.js';

export interface ListOptions {
  feature?: string;
}

interface Row {
  feature: string;
  id: string;
  hasIntake: boolean;
  planFile?: string;
  meta?: PlanMetadata;
}

export async function runList(opts: ListOptions): Promise<void> {
  const root = requireSquadRoot();
  const paths = buildPaths(root);
  const records = listStories(paths, { feature: opts.feature });
  const rows: Row[] = records.map((r) => {
    const planAbs = r.planFile ? path.join(paths.plansDir, r.feature, r.planFile) : undefined;
    const meta = planAbs ? readPlanMetadata(planAbs) : undefined;
    return {
      feature: r.feature,
      id: r.id,
      hasIntake: true,
      planFile: r.planFile,
      meta,
    };
  });

  if (rows.length === 0) {
    ui.info('(no stories yet — try `squad new-story <feature-slug>`)');
    return;
  }

  const header = ['feature', 'story', 'intake', 'plan', 'generated by'];
  const table = rows.map((r) => [
    r.feature,
    r.id,
    r.hasIntake ? 'yes' : '—',
    r.planFile ?? ui.theme.dim('—'),
    r.meta?.generatedBy ?? (r.planFile ? 'copy-paste' : ui.theme.dim('—')),
  ]);
  printTable([header, ...table]);
}

function printTable(rows: string[][]): void {
  const widths = rows[0]!.map((_, i) => Math.max(...rows.map((r) => stripAnsi(r[i] ?? '').length)));
  for (const row of rows) {
    console.log(row.map((cell, i) => pad(cell, widths[i]!)).join('  '));
  }
}

function pad(s: string, width: number): string {
  const visible = stripAnsi(s).length;
  return s + ' '.repeat(Math.max(0, width - visible));
}

function stripAnsi(s: string): string {
  return s.replace(/\x1b\[[0-9;]*m/g, '');
}
