import fs from 'node:fs';
import path from 'node:path';
import type { SquadPaths } from './paths.js';

export interface StoryRecord {
  feature: string;
  id: string;
  intakePath: string;
  storyDir: string;
  planFile?: string;
  titleHint?: string;
}

const STORY_FILE = /^(\d{2,})-story-.+\.md$/;

/** Top-level feature directory names under `.squad/stories/`. */
export function listFeatures(paths: SquadPaths): string[] {
  if (!fs.existsSync(paths.storiesDir)) return [];
  return fs
    .readdirSync(paths.storiesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

/** All intakes; same rows as `listStories()` with no filter. */
export function listAllStories(paths: SquadPaths): StoryRecord[] {
  return listStories(paths);
}

export function listStories(paths: SquadPaths, opts: { feature?: string } = {}): StoryRecord[] {
  const rows: StoryRecord[] = [];
  if (!fs.existsSync(paths.storiesDir)) return rows;

  for (const feature of fs.readdirSync(paths.storiesDir, { withFileTypes: true })) {
    if (!feature.isDirectory()) continue;
    if (opts.feature && feature.name !== opts.feature) continue;
    const featureDir = path.join(paths.storiesDir, feature.name);
    for (const story of fs.readdirSync(featureDir, { withFileTypes: true })) {
      if (!story.isDirectory()) continue;
      const storyDir = path.join(featureDir, story.name);
      const intakePath = path.join(storyDir, 'intake.md');
      if (!fs.existsSync(intakePath)) continue;
      rows.push({
        feature: feature.name,
        id: story.name,
        intakePath,
        storyDir,
        planFile: findPlanFor(paths.plansDir, feature.name, story.name),
        titleHint: readTitleHint(intakePath),
      });
    }
  }
  return rows;
}

export function findPlanFor(plansDir: string, feature: string, storyId: string): string | undefined {
  const featureDir = path.join(plansDir, feature);
  if (!fs.existsSync(featureDir)) return undefined;
  for (const entry of fs.readdirSync(featureDir)) {
    if (!STORY_FILE.test(entry)) continue;
    if (entry.includes(storyId)) return entry;
  }
  return undefined;
}

export function findStoryByIntake(records: StoryRecord[], intakePath: string): StoryRecord | undefined {
  const target = normalizeIntakePath(intakePath.trim());
  return records.find((r) => normalizeIntakePath(r.intakePath) === target);
}

function normalizeIntakePath(p: string): string {
  const resolved = path.resolve(p);
  try {
    return fs.realpathSync(resolved);
  } catch {
    return resolved;
  }
}

export function readTitleHint(intakePath: string): string | undefined {
  try {
    const head = fs.readFileSync(intakePath, 'utf8').split('\n').slice(0, 3).join('\n');
    const m = head.match(/>\s*\*\*Title hint \(from CLI\):\*\*\s*(.+?)\s*$/m);
    return m?.[1]?.trim() || undefined;
  } catch {
    return undefined;
  }
}

export interface PlanMetadata {
  provider?: string;
  model?: string;
  generatedBy?: string; // e.g. "anthropic/claude-opus-4-x" or undefined for copy-paste plans
}

export function readPlanMetadata(planFileAbsPath: string): PlanMetadata {
  try {
    const first = fs.readFileSync(planFileAbsPath, 'utf8').split('\n', 1)[0] ?? '';
    const m = first.match(/^<!--\s*squad-kit:\s*generated by\s+([^\s,]+)/);
    if (!m) return {};
    const generatedBy = m[1]!;
    const [provider, model] = generatedBy.split('/');
    return { provider, model, generatedBy };
  } catch {
    return {};
  }
}
