import fs from 'node:fs';
import path from 'node:path';
import type { SquadPaths } from './paths.js';

export interface StoryRecord {
  feature: string;
  id: string;
  intakePath: string;
  storyDir: string;
  planFile?: string;
  titleHint?: string;
}

const STORY_FILE = /^(\d{2,})-story-.+\.md$/;

/** Top-level feature directory names under `.squad/stories/`. */
export function listFeatures(paths: SquadPaths): string[] {
  if (!fs.existsSync(paths.storiesDir)) return [];
  return fs
    .readdirSync(paths.storiesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

/** Feature slugs that have a `plans/<feature>/` tree (union of story features and plan-only dirs). */
export function listPlanFeatureNames(paths: SquadPaths): string[] {
  const names = new Set(listFeatures(paths));
  if (fs.existsSync(paths.plansDir)) {
    for (const e of fs.readdirSync(paths.plansDir, { withFileTypes: true })) {
      if (e.isDirectory()) names.add(e.name);
    }
  }
  return [...names].sort();
}

/** All intakes; same rows as `listStories()` with no filter. */
export function listAllStories(paths: SquadPaths): StoryRecord[] {
  return listStories(paths);
}

export function listStories(paths: SquadPaths, opts: { feature?: string } = {}): StoryRecord[] {
  const rows: StoryRecord[] = [];
  if (!fs.existsSync(paths.storiesDir)) return rows;

  for (const feature of fs.readdirSync(paths.storiesDir, { withFileTypes: true })) {
    if (!feature.isDirectory()) continue;
    if (opts.feature && feature.name !== opts.feature) continue;
    const featureDir = path.join(paths.storiesDir, feature.name);
    for (const story of fs.readdirSync(featureDir, { withFileTypes: true })) {
      if (!story.isDirectory()) continue;
      const storyDir = path.join(featureDir, story.name);
      const intakePath = path.join(storyDir, 'intake.md');
      if (!fs.existsSync(intakePath)) continue;
      rows.push({
        feature: feature.name,
        id: story.name,
        intakePath,
        storyDir,
        planFile: findPlanFor(paths.plansDir, feature.name, story.name),
        titleHint: readTitleHint(intakePath),
      });
    }
  }
  return rows;
}

export function findPlanFor(plansDir: string, feature: string, storyId: string): string | undefined {
  const featureDir = path.join(plansDir, feature);
  if (!fs.existsSync(featureDir)) return undefined;
  const candidates: string[] = [];
  for (const entry of fs.readdirSync(featureDir)) {
    if (!STORY_FILE.test(entry)) continue;
    if (entry.includes(storyId)) candidates.push(entry);
  }
  if (candidates.length === 0) return undefined;
  const complete = candidates.find((e) => !e.endsWith('.partial.md'));
  return complete ?? candidates[0];
}

export function findStoryByIntake(records: StoryRecord[], intakePath: string): StoryRecord | undefined {
  const target = normalizeIntakePath(intakePath.trim());
  return records.find((r) => normalizeIntakePath(r.intakePath) === target);
}

function normalizeIntakePath(p: string): string {
  const resolved = path.resolve(p);
  try {
    return fs.realpathSync(resolved);
  } catch {
    return resolved;
  }
}

export function readTitleHint(intakePath: string): string | undefined {
  try {
    const raw = fs.readFileSync(intakePath, 'utf8');
    const head = raw.split('\n').slice(0, 30).join('\n');
    const hintLine = head.match(/>\s*\*\*Title hint \(from CLI\):\*\*\s*(.+?)\s*$/m);
    const fromHint = hintLine?.[1]?.trim();
    if (fromHint) return fromHint;

    // Anchor heading: `### Description` in a tracker preamble contains the substring `## Description`.
    const titleFence = raw.match(/(?:^|\n)## Title\b[\s\S]*?\n```(?:[\w-]*)?\s*\n([\s\S]*?)\n```/);
    const fromFence = titleFence?.[1]?.trim();
    if (fromFence) return fromFence;
    return undefined;
  } catch {
    return undefined;
  }
}

export interface PlanMetadata {
  provider?: string;
  model?: string;
  generatedBy?: string; // e.g. "anthropic/claude-opus-4-x" when the plan header includes squad-kit metadata
}

const PLAN_GENERATED_BY = /^<!--\s*squad-kit:\s*generated by\s+([^\s,]+)/;
const PLAN_ANY_SQUAD = /^<!--\s*squad-kit:\s*(.+?)\s*-->$/;

const MAX_FREEFORM_META_LEN = 96;

function parsePlanMetadataLine(line: string): PlanMetadata | null {
  const strict = line.match(PLAN_GENERATED_BY);
  if (strict) {
    const generatedBy = strict[1]!;
    const [provider, model] = generatedBy.split('/');
    return { provider, model, generatedBy };
  }
  const any = line.match(PLAN_ANY_SQUAD);
  if (!any) return null;
  const inner = any[1]!.trim();
  const flex = inner.match(/^generated\s+by\s+([^\s,]+)/i);
  if (flex) {
    const generatedBy = flex[1]!;
    const [provider, model] = generatedBy.split('/');
    return { provider, model, generatedBy };
  }
  const short =
    inner.length > MAX_FREEFORM_META_LEN ? `${inner.slice(0, MAX_FREEFORM_META_LEN - 1)}…` : inner;
  return { generatedBy: short };
}

/**
 * Reads the first `<!-- squad-kit: … -->` line near the top of a plan file.
 * - API plans: `generated by provider/model, …` → splits provider / model for tooling.
 * - Other comments: exposes the inner text as `generatedBy` (truncated) so `squad list` is not blank.
 */
export function readPlanMetadata(planFileAbsPath: string): PlanMetadata {
  try {
    const raw = fs.readFileSync(planFileAbsPath, 'utf8').replace(/^\uFEFF/, '');
    const lines = raw.split(/\n/);
    const scan = Math.min(lines.length, 40);
    for (let i = 0; i < scan; i++) {
      const line = (lines[i] ?? '').replace(/\r$/, '').trim();
      if (!line) continue;
      const parsed = parsePlanMetadataLine(line);
      if (parsed) return parsed;
    }
    return {};
  } catch {
    return {};
  }
}
